//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Holder
    {
        public int acno { get; set; }
        public string acname { get; set; }
        public string actype { get; set; }
        public string acbranch { get; set; }
        public int acamount { get; set; }
        public int acpin { get; set; }
    }
}
