//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Admin
    {
        public int adminId { get; set; }
        public string adminName { get; set; }
        public string adminPass { get; set; }
    }
}
